apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: '{{ .Values.cluster }}'
  annotations:
    argocd.argoproj.io/sync-wave: "360"
  namespace: '{{ .Values.cluster }}'
  labels:
    cloud: 'Azure'
    region: '{{ .Values.provider.region }}'
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: 'all-openshift-clusters'
spec:
  baseDomain: {{ .Values.provider.baseDomain}} 
  clusterName: '{{ .Values.cluster }}'
  powerState: Running
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    azure:
      baseDomainResourceGroupName: {{ .Values.provider.resource_group }}
      credentialsSecretRef:
        name: {{ .Values.cluster }}-azure-creds
      region: {{ .Values.provider.region }}
  provisioning:
    installConfigSecretRef:
      name: {{ .Values.cluster }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .Values.cluster }}-ssh-private-key
    imageSetRef:
      name: {{ .Values.imageName }} 
  pullSecretRef:
    name: {{ .Values.cluster }}-pull-secret
