---
# Source: vault-multicluster/charts/vault/templates/clustersecretstore.yaml
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: secretstore-vault
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      version: "v1" # leave as v1
      path: ""  # added to every call to vault, needs to be co-ordinated with the external secret definition to build the path
      caBundle:
      auth:
        # points to a secret that contains a vault token, see below for example.
        # https://www.vultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          namespace: "external-secrets"
          key: "token"