---
# Source: vault-multicluster/charts/vault/templates/server-config-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
data:
  extraconfig-from-values.hcl: |-
    disable_mlock = true
    ui = true

    listener "tcp" {
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      tls_cert_file="/etc/vault-tls/tls.crt"
      tls_key_file="/etc/vault-tls/tls.key"
      tls_client_ca_file="/etc/vault-tls/ca.crt"
    }

    storage "raft" {
      path = "/vault/data"

      retry_join {
        leader_api_addr = "https://vault-0.aws0.vault-internal.vault.svc.clusterset.local:8200"
        leader_ca_cert_file = "/etc/vault-tls/ca.crt"
      }

      retry_join {
        leader_api_addr = "https://vault-1.aws0.vault-internal.vault.svc.clusterset.local:8200"
        leader_ca_cert_file = "/etc/vault-tls/ca.crt"
      }

      retry_join {
        leader_api_addr = "https://vault-2.aws0.vault-internal.vault.svc.clusterset.local:8200"
        leader_ca_cert_file = "/etc/vault-tls/ca.crt"
      }

      retry_join {
        leader_api_addr = "https://vault-0.aws1.vault-internal.vault.svc.clusterset.local:8200"
        leader_ca_cert_file = "/etc/vault-tls/ca.crt"
      }

      retry_join {
        leader_api_addr = "https://vault-1.aws1.vault-internal.vault.svc.clusterset.local:8200"
        leader_ca_cert_file = "/etc/vault-tls/ca.crt"
      }

      retry_join {
        leader_api_addr = "https://vault-2.aws1.vault-internal.vault.svc.clusterset.local:8200"
        leader_ca_cert_file = "/etc/vault-tls/ca.crt"
      }

      retry_join {
        leader_api_addr = "https://vault-0.azure0.vault-internal.vault.svc.clusterset.local:8200"
        leader_ca_cert_file = "/etc/vault-tls/ca.crt"
      }

      retry_join {
        leader_api_addr = "https://vault-1.azure0.vault-internal.vault.svc.clusterset.local:8200"
        leader_ca_cert_file = "/etc/vault-tls/ca.crt"
      }

      retry_join {
        leader_api_addr = "https://vault-2.azure0.vault-internal.vault.svc.clusterset.local:8200"
        leader_ca_cert_file = "/etc/vault-tls/ca.crt"
      }

    }

    log_level = "debug"

    service_registration "kubernetes" {}