---
# Source: vault-multicluster/charts/vault/templates/server-kluster-clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: statefulset-get-klusterlet-rolebinding
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
roleRef:
  kind: ClusterRole
  name: statefulset-get-klusterlet-role
  apiGroup: rbac.authorization.k8s.io