---
# Source: vault-multicluster/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-nonroot-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allow-nonroot-scc
subjects:
- kind: ServiceAccount
  name: vault
  namespace: vault