---
# Source: vault-multicluster/templates/kms-cloud-credential-gcp.yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: vault-kms-gcp
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    predefinedRoles:
      - roles/cloudkms.cryptoKeyEncrypterDecrypter
  secretRef:
    name: kms-cloud-credentials
    namespace: vault
---
# Source: vault-multicluster/templates/kms-cloud-credential-aws.yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: vault-kms-aws
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - kms:Encrypt
      - kms:Decrypt
      - kms:DescribeKey
      effect: Allow
      resource: '*'
  secretRef:
    name: kms-cloud-credentials
    namespace: vault