global:
  tlsDisable: false
  openshift: true

clusterNames:
  - aws0 
  - aws1
  - azure0

global_base_domain: global.ibmsbaasonaws.com 

vault:  
  ui:
    enabled: true
  server:
    image: 
      tag: 1.8.1
    multicluster:
      enabled: true 
      cluster: 
    extraVolumes:
      - type: 'secret'
        name: 'vault-tls'
        path: '/etc'                 
    ha:
      replicas: 3
      enabled: true
      raft:
        enabled: true
        setNodeId: true
        config: |
          ui = true

          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file="/etc/vault-tls/tls.crt"
            tls_key_file="/etc/vault-tls/tls.key"
            tls_client_ca_file="/etc/vault-tls/ca.crt"          
          }

          storage "raft" {
            path = "/vault/data"
    
            retry_join {
              leader_api_addr = "https://vault-0.aws0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-1.aws0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-2.aws0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }            

            retry_join {
              leader_api_addr = "https://vault-0.aws1.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-1.aws1.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-2.aws1.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }               

            retry_join {
              leader_api_addr = "https://vault-0.azure0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-1.azure0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }      

            retry_join {
              leader_api_addr = "https://vault-2.azure0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }                              

          }

          log_level = "debug"

          service_registration "kubernetes" {}  
    affinity: |
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: vault
                app.kubernetes.io/instance: vault
                component: server
            topologyKey: failure-domain.beta.kubernetes.io/zone        
  injector:
    extraEnvironmentVars: 
      AGENT_INJECT_SET_SECURITY_CONTEXT: "false"
    image:
      repository: "docker.io/hashicorp/vault-k8s"
      tag: "0.11.0"      

