# Creates a ManagedClusterSetBinding to the openshift-gitops project
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSetBinding
metadata:
  name: multicloud-cluster-set
  namespace: openshift-gitops
spec:
  clusterSet: multicloud-cluster-set