---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: multicloud-cluster-set
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
          cluster.open-cluster-management.io/clusterset: multicloud-cluster-set
        # matchExpressions:
        # # - key: vendor
        # #   operator: "In"
        # #   values:
        # #   - OpenShift
        # - key: local-cluster
        #   operator: "NotIn"
        #   values:
        #   - "true"
        