kind: Kustomization

resources:
  - deployment.yaml
  - cr-secret-controller.yaml
  - cr-secret-edit.yaml
  - cr-secret-view.yaml
  - crb-secrets-controller.yaml
  - crd-clustersecretstore.yaml
  - crd-externalsecrets.yaml
  - crd-secretstore.yaml
  - rb-secrets-leaderelection.yaml
  - role-secrets-leaderelection.yaml
  - serviceaccount.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/external-secrets/external-secrets:v0.3.11
    target:
      kind: Deployment 
      name: external-secrets